Feature/order by default
vtex-apps/product-summary pull request #284
Opened 2020-11-10 13:54 UTC by victorhmp

#### What problem is this solving?

#### How to test it?

[Workspace](Link goes here!)

#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2020-11-10 16:23 UTC, klzns requested changes

2020-11-10 16:23 UTC, klzns commented on react/ProductSummaryList.js
> +    orderBy = ORDER_BY_OPTIONS.DEFAULT.value,
Shouldn't it be RELEVANCE?
```suggestion
    orderBy = ORDER_BY_OPTIONS.RELEVANCE.value,
```

2020-11-10 21:24 UTC, victorhmp commented on react/ProductSummaryList.js
> +    orderBy = ORDER_BY_OPTIONS.DEFAULT.value,
Yeeees!!

2020-11-11 18:36 UTC, klzns approved these changes

2020-11-11 18:50 UTC, kaisermann approved these changes

2020-11-11 18:56 UTC, icazevedo approved these changes

2020-11-13 12:58 UTC, merged