Migrate list to TS and add new prop analyticsListName
vtex-apps/product-summary pull request #287
Opened 2020-12-02 01:42 UTC by klzns

#### What problem is this solving?

Make it possible to add a name to the list of products so it can be used by Google Analytics.

#### How to test it?

https://summary--storecomponents.myvtex.com/

#### Screenshots or example usage:

![image](https://user-images.githubusercontent.com/284515/100817186-5be3f600-3426-11eb-8e55-df1ea2100c85.png)

![image](https://user-images.githubusercontent.com/284515/100817067-30610b80-3426-11eb-8c72-41dabefac604.png)

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

Depends on: https://github.com/vtex-apps/store-resources/pull/141

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2020-12-07 11:32 UTC, guerreirobeatriz approved these changes

2020-12-08 11:47 UTC, vitorflg approved these changes

2020-12-08 18:28 UTC, kaisermann requested changes

2020-12-08 18:28 UTC, kaisermann commented on react/ProductSummaryList.tsx
> +    QueryProductsTypes.Variables
ni ni ni ni niceeee

2020-12-08 18:28 UTC, kaisermann commented on react/ProductSummaryList.tsx
> +      if (actionOnProductClick) actionOnProductClick(product)
```suggestion
      actionOnProductClick?.(product)
```

2020-12-08 18:33 UTC, kaisermann approved these changes

2020-12-08 18:33 UTC, kaisermann commented on react/utils/normalize.ts
> +      commertialOffer.AvailableQuantity > 0
```suggestion
      commertialOffer?.AvailableQuantity > 0
```

2020-12-08 18:40 UTC, merged