Feature/hover image index criteria
vtex-apps/product-summary pull request #292
Opened 2020-12-16 18:38 UTC by icazevedo

#### What problem is this solving?

This PR is derived from [product-summary#283](https://github.com/vtex-apps/product-summary/pull/283). I couldn't contribute to the other PR to make it backwards compatible.

This PR adds the `index` criteria for matching product images when hovering and it also fixes a bug where the main product image would still show when the hover image was transparent.

#### How to test it?

[Workspace](https://icaropscriteria--storecomponents.myvtex.com/apparel---accessories/)

@imdanielpiva I've linked this version on the `icarovtex` workspace on the `tokstokio` account. I couldn't configure it via side editor, but it should work just fine.

#### Screenshots or example usage:

![](https://user-images.githubusercontent.com/26178791/98266977-a4b0a800-1f69-11eb-9b36-fa2fe2e60ffb.gif)

#### Related to / Depends on

This PR depends on [product-summary#288](https://github.com/vtex-apps/product-summary/pull/288) and should only be merged after it.

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/Q7vMieVa8cK0FgKqlr/giphy.gif)

2020-12-16 19:12 UTC, klzns requested changes
Needs rebase

2020-12-16 21:02 UTC, kaisermann approved these changes

2020-12-18 13:45 UTC, klzns approved these changes

2020-12-18 14:29 UTC, guerreirobeatriz approved these changes

2020-12-18 14:34 UTC, merged

2020-12-18 14:36 UTC, icazevedo commented
@allcontributors add @imdanielpiva for code