Add class to parent that holds the vtex-product-summary-2-x-item
vtex-apps/product-summary pull request #315
Opened 2021-05-30 16:58 UTC by carlosviniciusananias

**What problem is this solving?**
The block is encapsulated by a div with generic classes (_inline-flex justify-end absolute w-100 bottom-0 left-0_) which makes it impossible to apply styling... By applying cssHandles to this div we will now be able to position it as needed.

**Add in ProductSummaryImage.tsx**
```
Line 23:
const CSS_HANDLES = [
  ...
  'summaryItemContainer',
] as const

-

Line 157: 
function CollectionWrapper({
  ...
  classes,

-

Line 165: const { handles } = useCssHandles(CSS_HANDLES, { classes })

-

Line 168:
<CollectionBadges collectionBadgesText={collections} className={handles.summaryItemContainer}>
```

**A small example**

![Captura de tela de 2021-05-30 13-45-32](https://user-images.githubusercontent.com/32168339/120112935-7507fe00-c14e-11eb-8cb7-3892610c31d5.png)

**How does this PR make you feel? 🔗**

![image](https://user-images.githubusercontent.com/32168339/102024084-89a63480-3d6e-11eb-8412-b47509d4d9e2.png)

2021-05-31 18:48 UTC, victorhmp commented
Hi @carlosviniciusananias !
Thanks for the pull request! Could you please provide a workspace with this code linked?

2021-06-09 20:12 UTC, icazevedo requested changes
Thanks for the PR! As @victorhmp said, please fix the lint errors, add docs and a changelog entry :)

2021-06-09 20:12 UTC, icazevedo commented on react/ProductSummaryImage.tsx
> +  classes,
You should type this prop like [this](https://github.com/vtex-apps/product-summary/blob/1d908de85f310541f058e0449a2aa553b8a1f783/react/ProductSummarySKUName.tsx#L11).

2021-06-09 20:12 UTC, icazevedo commented on react/ProductSummaryImage.tsx
> +  const { handles } = useCssHandles(CSS_HANDLES, { classes })
React hooks cannot be called conditionally. Move it above the `if`.

2021-07-07 17:12 UTC, igorbrasileiro requested changes
Add CHANGELOG

2021-07-26 18:03 UTC, victorhmp commented
Closing this since due to it being stale.

2021-07-26 18:03 UTC, closed without merging