create RelatedProductList with list.context
vtex-apps/product-summary pull request #347
Opened 2022-01-14 17:09 UTC by Luis-eplus

#### What problem is this solving?

Make the use of related products shelf more consistent with regular shelf

#### How to test it?

Add `list-context.related-product-list` in your store theme, with the `slider-layout` as children and `product-summary.shelf` as block

[Workspace](https://luis--lojasupersaudavel.myvtex.com/)

#### Screenshots or example usage:

![image](https://user-images.githubusercontent.com/86304045/149555952-5069ec98-5f1a-496f-8b34-c298e55e1b74.png)

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/8m4R4pvViWtRzbloJ1/giphy.gif))

2022-01-21 11:57 UTC, sheilagomes commented on messages/context.json
> +  "admin/editor.productSummary.trackListName.title": "Should track list name",
```suggestion
  "admin/editor.productSummary.trackListName.title": "Should track list name",
  >>>>> "admin/editor.productSummary.trackListName.title": "Track list name",
```

2022-01-21 11:57 UTC, sheilagomes commented on messages/en.json
> +  "admin/editor.productSummary.trackListName.title": "Should track list name",
```suggestion
  "admin/editor.productSummary.trackListName.title": "Should track list name",
```  >>>>> "admin/editor.productSummary.trackListName.title": "Track list name",

2022-01-21 13:25 UTC, sheilagomes requested changes

2022-01-21 13:25 UTC, sheilagomes commented on messages/en.json
> +  "admin/editor.productSummary.trackListName.title": "Should track list name",
```suggestion
  "admin/editor.productSummary.trackListName.title": "Track list name",
```

2022-01-21 13:25 UTC, sheilagomes commented on messages/en.json
> +  "admin/editor.productSummaryRelatedList.description": "A related products shelf to show view recommendations",
```suggestion
  "admin/editor.productSummaryRelatedList.description": "A window display showing product recommendations for the user to view",
```

2022-01-21 13:25 UTC, sheilagomes commented on messages/en.json
> +  "admin/editor.productSummaryRelatedList.recommendation.description": "Which recommendations will be shown",
```suggestion
  "admin/editor.productSummaryRelatedList.recommendation.description": "Recommendations that will be shown",
```

2022-01-21 13:25 UTC, sheilagomes commented on messages/en.json
> +  "admin/editor.productSummaryRelatedList.view": "Who saw this, also saw...",
```suggestion
  "admin/editor.productSummaryRelatedList.view": "People who viewed this also viewed...",
```

2022-01-21 13:25 UTC, sheilagomes commented on messages/en.json
> +  "admin/editor.productSummaryRelatedList.viewAndBought": "Who saw this, also bought...",
```suggestion
  "admin/editor.productSummaryRelatedList.accessories": "Accessories",
  "admin/editor.productSummaryRelatedList.viewAndBought": "People who saw this, also bought...",
```

2022-01-21 13:25 UTC, sheilagomes commented on messages/es.json
> +  "admin/editor.productSummaryRelatedList.description": "Una vitrina de productos relacionados para mostrar recomendaciones de vista",
```suggestion
  "admin/editor.productSummary.trackListName.title": "Rastrear el nombre de la lista",
  "admin/editor.productSummaryRelatedList.title": "Productos relacionados",
  "admin/editor.productSummaryRelatedList.description": "Una vitrina de productos recomendados para ver",
```

2022-01-21 13:25 UTC, sheilagomes commented on messages/es.json
> +  "admin/editor.productSummaryRelatedList.recommendation.description": "Qué recomendaciones se mostrará",
```suggestion
  "admin/editor.productSummaryRelatedList.recommendation.description": "Recomendaciones que se mostrarán",
```

2022-01-21 13:25 UTC, sheilagomes commented on messages/pt-BR.json
> +  "admin/editor.productSummaryRelatedList.title": "Produtos Relacionados",
```suggestion
  "admin/editor.productSummaryRelatedList.title": "Produtos relacionados",
```

2022-01-21 13:25 UTC, sheilagomes commented on messages/pt.json
> +  "admin/editor.productSummaryRelatedList.title": "Produtos Relacionados",
```suggestion
  "admin/editor.productSummaryRelatedList.title": "Produtos relacionados",
```

2022-01-24 12:02 UTC, sheilagomes approved these changes
LGTM

2022-04-25 11:27 UTC, victorgrodriguesm7 commented
Any ETA for this being merged ? I started a new project where this Shelf is needed. Since the ProductSummary does not have this type of Shelf and the old Lib(`vtex.shelf`) is deprecated, I need to know if this merge will happen soon.

2024-08-26 17:46 UTC, closed without merging