Doc/update
vtex-apps/product-summary pull request #351
Opened 2022-03-02 14:10 UTC by Mariana-Caetano

#### What problem is this solving?

Update the documentation with images, fixed links, and a new section (in some of them).

2022-03-30 20:57 UTC, carolinamenezes commented on docs/ProductSummaryAttachmentList.md
> +Product Summary Attachment is a block exported by the [Product Summary app](https://developers.vtex.com/vtex-developer-docs/docs/vtex-product-summary) responsible for rendering a list of [attachments
```suggestion
Product Summary Attachment is the block exported by the [Product Summary app](https://developers.vtex.com/vtex-developer-docs/docs/vtex-product-summary) responsible for rendering the [attachment](https://help.vtex.com/en/tutorial/o-que-e-um-anexo--aGICk0RVbqKg6GYmQcWUm) options available for a product.
```

2022-03-31 13:36 UTC, carolinamenezes requested changes

2022-03-31 13:36 UTC, carolinamenezes commented on docs/ProductSummaryShelf.md
> +> Do not forget to also declare the other Product Summary's blocks in your theme, otherwise the component won't be displayed.
```suggestion
> Remember to define the other Product Summary blocks in your theme as well, otherwise the component will not be displayed.
```

2022-03-31 13:36 UTC, carolinamenezes commented on docs/ProductSummarySpecificationBadges.md
> +> The Product Specification Badges block has been deprecated in favor of the [Product Specifications](https://developers.vtex.com/vtex-developer-docs/docs/vtex-product-specifications) from the app `v
```suggestion
> The Product Specification Badges block has been deprecated in favor of the [Product Specifications](https://developers.vtex.com/vtex-developer-docs/docs/vtex-product-specifications) app. Although support for this block is still available, we strongly recommend that you update your store theme with the Product Specifications app to stay up with the component's evolution.
```

2022-03-31 13:36 UTC, carolinamenezes commented on docs/ProductSummaryShelf.md
> +2. Add the `product-summary.shelf` block as child of the [`list-context.product-list` block](https://developers.vtex.com/vtex-developer-docs/docs/vtex-product-summary-productsummarylist#product-list-
```suggestion
2. Add the `product-summary.shelf` block as a child of the [`list-context.product-list` block](https://developers.vtex.com/vtex-developer-docs/docs/vtex-product-summary-productsummarylist#product-list-block) :
```

2022-03-31 13:36 UTC, carolinamenezes commented on docs/ProductSummarySpecificationBadges.md
> +In order to apply CSS customizations in this and other blocks, follow the instructions given in the recipe on [Using CSS Handles for store customization](https://developers.vtex.com/vtex-developer-do
```suggestion
To apply CSS customizations in this and other blocks, follow the [Using CSS Handles for store customization](https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-using-css-handles-for-store-customization) guide.
```

2022-03-31 13:36 UTC, carolinamenezes commented on docs/README.md
> +| [`list-context.product-list`](https://developers.vtex.com/vtex-developer-docs/docs/vtex-product-summary-productsummarylist) | ![https://img.shields.io/badge/-Mandatory-red](https://img.shields.io/b
```suggestion
| [`list-context.product-list`](https://developers.vtex.com/vtex-developer-docs/docs/vtex-product-summary-productsummarylist) | ![https://img.shields.io/badge/-Mandatory-red](https://img.shields.io/badge/-Mandatory-red) Renders the list of products in the Product Summary component. It fetches product data and provides it to the `product-summary.shelf` block. This block, then, provides its child blocks with the product data. | 
```

2022-03-31 13:36 UTC, carolinamenezes commented on docs/README.md
> +| `product-summary-price` | ![https://img.shields.io/badge/-Deprecated-red](https://img.shields.io/badge/-Deprecated-red) The Product Summary Price block, responsible for rendering the product price,
```suggestion
| `product-summary-price` | ![https://img.shields.io/badge/-Deprecated-red](https://img.shields.io/badge/-Deprecated-red) Renders the product price. This block has been deprecated in favor of the [Product Price](https://developers.vtex.com/vtex-developer-docs/docs/vtex-product-price) app. Although support for this block is still available, we strongly recommend that you use the Product Price app. | 
```

2022-03-31 13:36 UTC, carolinamenezes commented on docs/README.md
> +| [`product-summary-buy-button`](https://vtex.io/docs/components/all/vtex.product-summary/product-summary-buy-button) | Renders the Buy Button. Notice that this block should only be configured if you
```suggestion
| [`product-summary-buy-button`](https://vtex.io/docs/components/all/vtex.product-summary/product-summary-buy-button) | Renders the Buy Button. This block must be configured only if your store uses the [Minicart v1](https://github.com/vtex-apps/minicart/blob/383d7bbd3295f06d1b5854a0add561a872e1515c/docs/README.md). If your store uses the [Minicart v2](https://developers.vtex.com/vtex-developer-docs/docs/vtex-minicart), please configure the [**Add To Cart Button**](https://developers.vtex.com/vtex-developer-docs/docs/vtex-add-to-cart-button) instead.  | 
```

2022-03-31 13:36 UTC, carolinamenezes commented on docs/README.md
>  2. Add the `list-context.product-list` block to the store theme template where you desire to display a product list and declare the `product-summary.shelf` in its block list. For example:
```suggestion
2. Add the `list-context.product-list` block to a store template of your choice and declare the `product-summary.shelf` in its block list. For example:
```

2022-03-31 13:36 UTC, carolinamenezes commented on docs/README.md
> +> Notice that although the `product-summary.shelf` refers to the shelf component in its name, the block does not need to be necessarily used  when building a Shelf component. It can and should be use
```suggestion
> Although the name of the block 'product-summary.shelf' alludes to the Shelf component, this block is not required to create a Shelf component. The Product Summary Shelf is used to present summary product information in other components, such as the [Minicart](https://developers.vtex.com/vtex-developer-docs/docs/vtex-minicart) and the [Search Results](https://developers.vtex.com/vtex-developer-docs/docs/vtex-search-result) page.
```

2022-03-31 13:36 UTC, carolinamenezes commented on docs/README.md
> +3. Based on the product information you desire to have rendered in the product list, choose which blocks from the exported list above will be sent as the `product-summary.shelf` children. In a scenar
```suggestion
3. Add the blocks from the list above as children of the `product-summary.shelf`, considering the product information you want to present in the product list. Take the following example in which the product name, description, image, price, SKU selector, and Buy Button are all displayed in the Product Summary:
```

2022-03-31 13:36 UTC, carolinamenezes commented on docs/README.md
> +> In order to configure and better understand each of the Product Summary exported blocks, go through their respective documentation.
```suggestion
```

2022-04-04 21:16 UTC, Mariana-Caetano commented
@carolinamenezes changes updated. Can you approve it? Thanks!

2022-04-18 13:05 UTC, carolinamenezes approved these changes

2022-04-19 16:44 UTC, Mariana-Caetano commented on CHANGELOG.md
> +### Updated
```suggestion
### Changed
```

2022-04-20 14:49 UTC, icazevedo approved these changes

2022-04-20 14:50 UTC, merged